### ISSUE TITLE
flyoobe Select ISO from Computer Powershell error

### ISSUE THREAD

**Issue by TheBeardofKnowledge** [builtbybel/Flyby11#266]
Belim,

Thank you for your hard work on these wonderful releases.  Long time Fan of Crapfixer and aboslutely love Flyby11 classic.

For this new release of flyoobe (amazing idea by the way) there is an error when choosing an ISO from folder at the powershell ISO load script.  Here are the details:
Selecting an iso from local computer performs the pre-checks ok but errors out when powershell tries to mount the iso.  This happens with all ISO files at attempting to load.
"Powershell error during mount: try {
$iso = Mount-DiskImage -ImagePath 'e:\windows11\win11_24h2_english_x64.sio' -PassThru
-ErrorAction Stop
$volumes = Get-Volume -DiskImage $iso -ErrorAction Stop
#Korrektur hier: Trrim() als Methode auf dem String
aufrufen
$driveLetter = ($volumes.DriveLetter | Out-String).Trim()
$driveLetter
} catch {
Write-Error $_.Exection.Message
exit 1 # Indicate an error
}
: Invalid property
+CategoryInfo     : NotSpecified: (:) {Write-Error},
WriteErrorException
+ FullyQualifiedErrorId 👍 Microsoft.PowerShell.Commands.WriteErrorException
Final error: System.InvalidOperationException: ISO mounting returned no drive letter.

Environment is Windows 10 Pro Enterprise 22H2 and powershell 5.1.19041.6093

<img width="1161" height="848" alt="Image" src="https://github.com/user-attachments/assets/68c7c21c-5b52-4f34-b7a9-e67b864bc4f3" />

**Comment by TheBeardofKnowledge** [comment]
I am unsure of this, but perhaps it is simply the use of ' instead of " after -ImagePath.  The Microsoft documentation examples indicate the use of "isofilepath"

**Comment by Belim** [comment]
@TheBeardofKnowledge hi, the problem isnt the wrong parameter name. i see a typo in the file extension “iso”,  you wrote “sio”. or it could be that windows isnt assigning a drive letter to the mounted iso. do you have other disks mounted? how many drive letters are already in use? in the upcoming 1.2 release i made the code a bit more robust so it filters volumes to only those that actually have a drive letter

**Comment by TheBeardofKnowledge** [comment]
Belim, thanks for replying! That was completely a typo on my part.  I should have copied/pasted from log file instead of writing it all out.
This system iactually does have something odd about it.  After my comment I went to go try it on 2 other systems and it worked perfectly.
The system that it wouldn't work on has 2 local physical drives c: d: and one network drive g:
No iso's were mounted at the time.  Also worth mentioning that on this system the classic flyby11 wouldn't work either, so there's that.  Maybe the built-in powershell has a problem.
This successfully upgraded 2 workstations that WERE NOT windows 11 compatible.

**Comment by TheBeardofKnowledge** [comment]
Hi Belim, I made a video on FlyOOBE and posted it to my Youtube.  Hopefully this will get more people using it.  Thank you for creating this!

**Comment by Belim** [comment]
@TheBeardofKnowledge hi, cool, do you have a link for me?

**Comment by TheBeardofKnowledge** [comment]
@Belim and anyone that runs into this issue:
Ran this through a few more computers and also got some feedback from others that tried it; those computers that get a powershell error when loading the iso return the error: 0x80041031 metadataerror.
(I removed "-ErrorAction Stop" to see the actual result code while performing the actions manually in powershell)

Traced this back to WMI (Windows Management Instrumentation) issues on the specific pc.

FIXED IT WITH THESE COMMANDS:

Run Elevated command prompt:
# Disable and stop the WMI service

sc config winmgmt start= disabled
net stop winmgmt

# Run the following commands

Winmgmt /salvagerepository %windir%\System32\wbem
Winmgmt /resetrepository %windir%\System32\wbem
 
# Re-enable the WMI service and reboot (optional)

sc config winmgmt start= auto

**Comment by plao** [comment]
> [@Belim](https://github.com/Belim) and anyone that runs into this issue: Ran this through a few more computers and also got some feedback from others that tried it; those computers that get a powershell error when loading the iso return the error: 0x80041031 metadataerror. (I removed "-ErrorAction Stop" to see the actual result code while performing the actions manually in powershell)
> 
> Traced this back to WMI (Windows Management Instrumentation) issues on the specific pc.
> 
> FIXED IT WITH THESE COMMANDS:
> 
> Run Elevated command prompt:
> # Disable and stop the WMI service
> 
> sc config winmgmt start= disabled net stop winmgmt
> # Run the following commands
> 
> Winmgmt /salvagerepository %windir%\System32\wbem Winmgmt /resetrepository %windir%\System32\wbem
> # Re-enable the WMI service and reboot (optional)
> 
> sc config winmgmt start= auto

Thanks a lot Man!!!

**Comment by Jaapop8** [comment]
> [@Belim](https://github.com/Belim) and anyone that runs into this issue: Ran this through a few more computers and also got some feedback from others that tried it; those computers that get a powershell error when loading the iso return the error: 0x80041031 metadataerror. (I removed "-ErrorAction Stop" to see the actual result code while performing the actions manually in powershell)
> 
> Traced this back to WMI (Windows Management Instrumentation) issues on the specific pc.
> 
> FIXED IT WITH THESE COMMANDS:
> 
> Run Elevated command prompt:
> 
> # Disable and stop the WMI service
> sc config winmgmt start= disabled net stop winmgmt
> 
> # Run the following commands
> Winmgmt /salvagerepository %windir%\System32\wbem Winmgmt /resetrepository %windir%\System32\wbem
> 
> # Re-enable the WMI service and reboot (optional)
> sc config winmgmt start= auto

Unfortunately it didn't solve the issue for me....

**Comment by joshuarutland08-wq** [comment]
> [@Belim](https://github.com/Belim) and anyone that runs into this issue: Ran this through a few more computers and also got some feedback from others that tried it; those computers that get a powershell error when loading the iso return the error: 0x80041031 metadataerror. (I removed "-ErrorAction Stop" to see the actual result code while performing the actions manually in powershell)
> 
> Traced this back to WMI (Windows Management Instrumentation) issues on the specific pc.
> 
> FIXED IT WITH THESE COMMANDS:
> 
> Run Elevated command prompt:
> 
> # Disable and stop the WMI service
> sc config winmgmt start= disabled net stop winmgmt
> 
> # Run the following commands
> Winmgmt /salvagerepository %windir%\System32\wbem Winmgmt /resetrepository %windir%\System32\wbem
> 
> # Re-enable the WMI service and reboot (optional)
> sc config winmgmt start= auto

This didn't fix my it for my pc

**Comment by Jaapop8** [comment]
Why is this error closed? It is not fixed for me and more....

**Comment by joshuarutland08-wq** [comment]
i have no idea

**Comment by Jaapop8** [comment]
I created a new issue
https://github.com/builtbybel/FlyOOBE/issues/469

**Comment by joshuarutland08-wq** [comment]
alright

**Comment by MaXFalstein** [comment]
@Belim, can this issue be reopened?

**Comment by TheBeardofKnowledge** [comment]
So when this happens, it's a pain because what I've found is its some deep level corruption in the system that's just not being evident but can be found by tracing back event viewer logs.  The Fix is to run a procedural corruption fix on Windows 10.  I made a script for that (not stealing the limelight from Belim, just trying to help)
Here is the script:
https://github.com/TheBeardofKnowledge/Scripts-from-my-videos/blob/main/Fix-Windows-Corruption/Fix-OS-Corruption.bat

**Comment by Jaapop8** [comment]
@TheBeardofKnowledge Thx for your effort! Unfortunately I already took the Rufus route to go from W10 to W11 so I cannot test it..
